### ISSUE TITLE
Can't answer "neither" for temporary promotion

### ISSUE THREAD

**Issue by jonodrew** [jonodrew/talent-tracker#63]
the system currently forces users to say whether the promotion is temporary or substantive. There is a third option, where the candidate is not being promoted but instead is doing a level transfer.

There has to be a way for users to say "This is a level transfer". I propose we do this through the addition of another radio on the update/role view

**Comment by mforner13** [comment]
I am going to change the form to have a question 'Describe your job move' with 3 radio buttons: 
- 'Temporary promotion' 
- 'Substantive promotion'
- 'Level transfer'
